services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: notification_app

    restart: always

    ports:
      - "8000:8000"

    healthcheck:
      test:
        [
          "CMD",
          "python",
          "-c",
          "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"
        ]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully

    env_file:
      - .env

    volumes:
      - .:/app

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:16

    container_name: notification_db

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ens

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  migrations:
    build:
      context: .
      dockerfile: docker/migrations/Dockerfile

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env
  rabbitmq:
    image: rabbitmq:3-management
    container_name: notification_rabbitmq
    ports:
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7
    container_name: notification_redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  worker:
    build: .
    container_name: notification_worker
    command: celery -A app.celery_app.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  prometheus:
    image: prom/prometheus:latest
    container_name: notification_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      app:
        condition: service_healthy

  grafana:
    image: grafana/grafana:latest
    container_name: notification_grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  postgres_data:
