"""add delivery retry fields

Revision ID: a22a6029492a
Revises: 6efb60fe1215
Create Date: 2026-08-15 12:01:21.010552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22a6029492a'
down_revision: Union[str, Sequence[str], None] = '6efb60fe1215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    op.add_column('deliveries', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_delivery_status_next_attempt', 'deliveries', ['status', 'next_attempt_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_delivery_status_next_attempt', table_name='deliveries')
    op.drop_column('deliveries', 'next_attempt_at')
    op.drop_column('deliveries', 'attempts')
    # ### end Alembic commands ###
